<html>
<head>
	<title>PN Students Management Software - Deployment</title>
	<link rel="stylesheet" type="text/css" href="/static/theme/default/style/global.css"/>
	<link rel="stylesheet" type="text/css" href="/static/theme/default/style/section.css"/>
	<?php if (isset($header)) echo $header;?>
</head>
<body>
<div style='width:100%;height:100%;display:flex;flex-direction:column;justify-content:center;align-items:center;'>
	<div class='section' style='max-width:99%'>
		<div class='header' style='flex:none;display:flex;flex-direction:column;justify-content:center;align-items:center;'>
			<div>PN Students Management Software - Deployment</div>
		</div>
