<!DOCTYPE html>
<html>
<head>
	<title>PN Students Database</title>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
	<style type='text/css'>body,html{width:100%;height:100%;} body,html,table{margin:0px;padding:0px;font-family:Arial,Tahoma,Verdana;font-size:10pt;}</style>
</head>
<body onload="if (window != window.top) window.top.reload();">
<table id='__loading_table' style='width:100%;height:100%;margin:0px;padding:0px;z-index:100;background-color:white;position:fixed;top:0px;left:0px;'>
<tr><td valign=middle align=center>
<img src='/static/application/logo.png'/>
<br/>
<img src='/static/application/loading_100.gif'/>
<br/>
<span id='loading_status' style='font-size:8pt;color: #606060'></span>
</td></tr>
</table>
<script type='text/javascript' src='/dynamic/application/service/loading'></script>
</body>
</html>