<?php
class service_create_campaign extends Service{
	public function get_required_rights(){return array("manage_selection_campaign");}
	public function input_documentation(){
		?>
<ul>
	<li><code>name</code>: {string} the campaign name</li>
</ul>
<?php	
	}
	public function output_documentation(){
		echo "<ul>";
		echo "<li>{boolean} false if a problem occured</li>";
		echo "<li> {object} {key: id} where id is the one generated by inserting into the database</li>";
		echo "</ul>";
	}
	public function documentation(){echo "Create a selection campaign";}
	public function execute(&$component,$input){
		if(!isset($input["name"])) {echo "false"; return;}
		else{
			try{
				$key = $component->createCampaign($input["name"]);
			} catch(Exception $e) {
				PNApplication::error($e);
			}
			if(PNApplication::has_errors()) echo "false";
			else echo "{key:".$key."}";
		}
	}
}	
?>