<html>
<head>
	<title>Maintenance - PN Students Management Software</title>
	<link rel="stylesheet" type="text/css" href="?css=global"/>
	<link rel="stylesheet" type="text/css" href="?css=section"/>
	<?php if (isset($header)) echo $header;?>
</head>
<body>
<div style='width:100%;height:100%;display:flex;flex-direction:column;justify-content:center;align-items:center;'>
	<div class='section'>
		<div class='header' style='flex:none;display:flex;flex-direction:column;justify-content:center;align-items:center;'>
			<div>PN Students Management Software - Maintenance</div>
		</div>
